package router

import (
	"fmt"
	"sort"
	"strings"
)

// genRoute pairs a ServeMux route with the handler that serves it.
type genRoute struct {
	path    string
	handler string
}

// ghpRoutesTmpl is the fixed skeleton of ghproutes.go. The import block and
// the AddRoutes body are spliced into the two %s slots.
const ghpRoutesTmpl = `// Code generated by GHP. DO NOT EDIT.

package main

%s

func AddRoutes(mux *http.ServeMux) {
%s}
`

// GenRoutes returns the Go source for ghproutes.go, which registers every
// page in files on a ServeMux through AddRoutes. Pages in a subdirectory are
// imported as <module>/<RelDir> and referenced as PkgName.FuncName; pages at
// the root live in package main. Only the GET method is emitted for now.
// Ex: module "example.com/site", blog/[slug].ghp ->
// mux.HandleFunc("GET /blog/{slug}", blog.BlogSlug).
func GenRoutes(files []*GhpFile, module string) string {
	imports := map[string]bool{}
	routes := make([]genRoute, 0, len(files))

	for _, f := range files {
		handler := f.FuncName
		if f.RelDir != "" {
			handler = f.PkgName + "." + f.FuncName
			imports[module+"/"+f.RelDir] = true
		}
		routes = append(routes, genRoute{f.route(), handler})
	}

	sort.Slice(routes, func(i, j int) bool { return routes[i].path < routes[j].path })

	return fmt.Sprintf(ghpRoutesTmpl, importBlock(imports), routeBlock(routes))
}

// importBlock renders the import(...) block, or a single import when
// net/http is the only path. Ex: {"a/b", "net/http"} ->
// "import (\n\t\"a/b\"\n\t\"net/http\"\n)".
func importBlock(imports map[string]bool) string {
	imps := make([]string, 0, len(imports)+1)
	imps = append(imps, "net/http")
	for imp := range imports {
		imps = append(imps, imp)
	}
	sort.Strings(imps)

	if len(imps) == 1 {
		return fmt.Sprintf("import %q", imps[0])
	}

	lines := make([]string, 0, len(imps)+2)
	lines = append(lines, "import (")
	for _, imp := range imps {
		lines = append(lines, "\t"+fmt.Sprintf("%q", imp))
	}
	lines = append(lines, ")")
	return strings.Join(lines, "\n")
}

// routeBlock renders one mux.HandleFunc call per route, sorted by path.
// Ex: [{"/about", "About"}] ->
// "\tmux.HandleFunc(\"GET /about\", About)\n".
func routeBlock(routes []genRoute) string {
	lines := make([]string, 0, len(routes))
	for _, r := range routes {
		lines = append(lines, fmt.Sprintf("\tmux.HandleFunc(\"GET %s\", %s)", r.path, r.handler))
	}
	return strings.Join(lines, "\n") + "\n"
}
