package router

import (
	"fmt"
	"sort"
	"strings"
)

// genRoute pairs a ServeMux route with the handler that serves it.
type genRoute struct {
	path    string
	handler string
}

// GenRoutes returns the Go source for ghproutes.go, which registers every
// page in files on a ServeMux through AddRoutes. Pages in a subdirectory are
// imported as <module>/<RelDir> and referenced as PkgName.FuncName; pages at
// the root live in package main. Only the GET method is emitted for now.
// Ex: module "example.com/site", blog/[slug].ghp ->
// mux.HandleFunc("GET /blog/{slug}", blog.BlogSlug).
func GenRoutes(files []*GhpFile, module string) string {
	imports := map[string]bool{}
	routes := make([]genRoute, 0, len(files))

	for _, f := range files {
		handler := f.FuncName
		if f.RelDir != "" {
			handler = f.PkgName + "." + f.FuncName
			imports[module+"/"+f.RelDir] = true
		}
		routes = append(routes, genRoute{f.route(), handler})
	}

	sort.Slice(routes, func(i, j int) bool { return routes[i].path < routes[j].path })

	var b strings.Builder
	b.WriteString("// Code generated by GHP. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")

	imps := make([]string, 0, len(imports)+1)
	imps = append(imps, "\"net/http\"")
	for imp := range imports {
		imps = append(imps, fmt.Sprintf("\"%s\"", imp))
	}
	sort.Strings(imps)

	if len(imps) == 1 {
		c := fmt.Sprintf("import %s\n\n", imps[0])
		b.WriteString(c)
	} else {
		b.WriteString("import (\n")
		for _, imp := range imps {
			fmt.Fprintf(&b, "\t%s\n", imp)
		}
		b.WriteString(")\n\n")
	}

	b.WriteString("func AddRoutes(mux *http.ServeMux) {\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "\tmux.HandleFunc(\"GET %s\", %s)\n", r.path, r.handler)
	}
	b.WriteString("}\n")
	return b.String()
}
